#!/bin/sh
usage() {
echo "usage: bump-version <version-id>"
}

if [ $# -ne 1 ]; then
usage
exit 1
fi

sed -i "s/version [0-9]\+\.[0-9]\+\.[0-9]\+$/version $1/g" js/*.js
sed -i "s/version [0-9]\+\.[0-9]\+\.[0-9]\+$/version $1/g" css/*.css

#update version in download button
sed -i "s/[0-9]\+\.[0-9]\+\.[0-9]\+/$1/g" ../gh-pages/index.html

git commit -a -m"Bump version to $1"
